---
title: "Brave New World"
author: "Peter Licari"
date: '2020-03-01'
draft: yes
slug: brave-new-world
tags: []
categories: []
---

This is a stereotypical "first post on the blog post." I know that it's stereotypical because this isn't the first blog post that I've made. In fact, it's not even the first post I've made *__for this blog.__* 

This is the first post for a blog that's currently hosted on [www.awildpoliticalnerd.tumblr.com](Tumblr.) One that actually has a fair number of posts, actually. But while Tumblr is lovely for most, it's not all that well-adapted for people trying to publish data analyses or the like. It can do gifs easy enough, but not interactive visualizations. It also is a collosal pain to input chunks of code, so I couldn't really write any tutorials there in a way that flowed well, visually. It's also just a more visually-based platform in general---which, again, is totally great! But my mix of memes and longer, discursive text posts made it stick out like a sore thumb. 

I'd been hearing the siren song of github pages and `blogdown` calling to me for a while. Unlike Oedipus, I ultimately didn't stay lashed to the mast. Sites like these are more suited to the style of blog-content that I like to do: Shorter, less structured than an article; frequently consisting of memes and other visual things. I'm optimistic. We'll see how it goes!      